In [1]:
# Imporing Dataset
from sklearn.datasets import load_iris
iris_data = load_iris()

In [2]:
iris_features = iris_data.data
iris_target = iris_data.target

In [3]:
iris_data.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [4]:
iris_data.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [5]:
iris_features.shape

(150, 4)

In [7]:
iris_target.shape

(150,)

In [8]:
# Importing cross validation score
from sklearn.model_selection import cross_val_score

In [10]:
#Model building
#1. Logistic regression
from sklearn.linear_model import LogisticRegression
lr_model = LogisticRegression()
lr_score = cross_val_score(lr_model,iris_features,iris_target,cv=3)

C:\Users\wit5\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [11]:
lr_score

array([0.98, 0.96, 0.98])

In [13]:
import numpy as np
avg_lr_score = np.average(lr_score)
avg_lr_score

0.9733333333333333

In [15]:
#2. Random forest
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier()

rf_score = cross_val_score(rf_model,iris_features,iris_target,cv=3)

In [16]:
rf_score

array([0.98, 0.94, 0.98])

In [17]:
import numpy as np
avg_rf_score = np.average(rf_score)
avg_rf_score

0.9666666666666667

In [20]:
#3. Support Vetor Machine
from sklearn.svm import SVC
SVM_model = SVC()
SVM_score = cross_val_score(SVM_model,iris_features,iris_target,cv=3)

In [21]:
SVM_score

array([0.96, 0.98, 0.94])

In [22]:
import numpy as np
avg_SVM_score = np.average(SVM_score)
avg_SVM_score

0.96

In [24]:
model_comparision = {"Model":["Logistic Regression","Random Forest","Support Vector Machine"],
                     " 3-fold Cross validation score ":[lr_score,rf_score,SVM_score],
                     " Average Score ":[avg_lr_score,avg_rf_score,avg_SVM_score]}

In [26]:
import pandas as pd
modelComparision = pd.DataFrame(model_comparision)
modelComparision

Model  3-fold Cross validation score    Average Score 
0     Logistic Regression              [0.98, 0.96, 0.98]         0.973333
1           Random Forest              [0.98, 0.94, 0.98]         0.966667
2  Support Vector Machine              [0.96, 0.98, 0.94]         0.960000

In [27]:
x = iris_data.data
y = iris_data.target

In [28]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [30]:
lr_model.fit(x,y,3)

C:\Users\wit5\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [31]:
y_pred = lr_model.predict(x)

In [33]:
np.sum(y_pred!=y)

2

In [34]:
print(iris_data.target_names[lr_model.predict([[4.5,4.5,5.8,3.5]])])

['virginica']
